# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/azamk/Desktop/Vivzdo/modulator/modulator.cache/wt [current_project]
set_property parent.project_path C:/Users/azamk/Desktop/Vivzdo/modulator/modulator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/azamk/Desktop/Vivzdo/modulator/modulator.srcs/sources_1/new/modulator_pkg.vhd
  C:/Users/azamk/Desktop/Vivzdo/modulator/modulator.srcs/sources_1/new/sine.vhd
  C:/Users/azamk/Desktop/Vivzdo/modulator/modulator.srcs/sources_1/new/counter.vhd
  C:/Users/azamk/Desktop/Vivzdo/modulator/modulator.srcs/sources_1/new/frequency_trigger_rtl.vhd
  C:/Users/azamk/Desktop/Vivzdo/modulator/modulator.srcs/sources_1/new/sine_top.vhd
}
synth_design -top sine_top -part xc7z020clg484-1
write_checkpoint -noxdef sine_top.dcp
catch { report_utilization -file sine_top_utilization_synth.rpt -pb sine_top_utilization_synth.pb }
